### ISSUE TITLE
Double options on top bar

### ISSUE THREAD

**Issue by elgorditosalsero** [mallowigi/mtslack#122]
**Describe the bug**
Options are doubled in the top bar.

**To Reproduce**
1. Apply tweaks from devtools

**Expected behavior**
Have only one option

**Screenshots**
![Screenshot 2021-12-07 at 10 32 40](https://user-images.githubusercontent.com/65770455/145040012-edc8d3ad-1e0e-422f-8a2e-3a28ff2c98a9.png)

**Comment by mallowigi** [comment]
I know, it's a bit hard to debug as it wasn't intended to be use like that. In my case I have multiple workspaces so switching workspaces do the trick, but otherwise you could simply turn the tweaks off.

**Comment by elgorditosalsero** [comment]
@mallowigi Thx for the explanation 😄
