### ISSUE TITLE
Not working (macOS)

### ISSUE THREAD

**Issue by hrqmonteiro** [mallowigi/mtslack#194]
![Screen Shot 2022-08-15 at 21 23 35](https://user-images.githubusercontent.com/17055027/184758009-f18456ea-7673-4bd4-bc4f-d8363ca6f7f3.png)

**Comment by mallowigi** [comment]
You have a very old version, please update to the latest version

**Comment by hrqmonteiro** [comment]
> You have a very old version, please update to the latest version

What do you mean? Very old version of what?
Slack? Node? What?

I am using Node 16.16.0 and the latest version of Slack.

**Comment by mallowigi** [comment]
Old version of mtslack.
