### ISSUE TITLE
Allow enabling tweaks without themes

### ISSUE THREAD

**Issue by PSalant726** [mallowigi/mtslack#52]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to customize the fonts used by slack (including the monospace font) in a persistent way, without also applying the larger color theme. All of the tweaks seem to have toggles except for this one. The `/slackfont` command does not support this ask, since the font is reset on app restart.

**Describe alternatives you've considered**
If theming cannot be totally disabled, it would be satisfactory to include the default theme (or the ability to allow changes made by the built-in theme preferences), as part of the "loop over installed themes" cycle.

**Comment by mallowigi** [comment]
done

**Comment by PSalant726** [comment]
This is perfect! Thanks!
