### ISSUE TITLE
install issue on ubuntu 20.04

### ISSUE THREAD

**Issue by jellevanhees** [mallowigi/mtslack#53]
**Describe the bug**
version 15.0.0 doesn't run on ubuntu 20.04
```
Checking for updates...
Finished checking for updates!
(node:190919) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mtslack/node_modules/figlet/fonts/whimsy.flf'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Function.figlet.loadFontSync (/usr/local/lib/node_modules/mtslack/node_modules/figlet/lib/node-figlet.js:48:23)
    at Function.me.textSync (/usr/local/lib/node_modules/mtslack/node_modules/figlet/lib/figlet.js:879:43)
    at run (/usr/local/lib/node_modules/mtslack/main.js:12:35)
    at AutoUpdate.update.on (/usr/local/lib/node_modules/mtslack/main.js:60:13)
    at AutoUpdate.emit (events.js:198:13)
    at AutoUpdate.onCheck (/usr/local/lib/node_modules/mtslack/node_modules/cli-autoupdate/index.js:31:12)
    at callback (/usr/local/lib/node_modules/mtslack/node_modules/cli-autoupdate/index.js:18:37)
    at UpdateNotifier.<anonymous> (/usr/local/lib/node_modules/mtslack/node_modules/update-notifier/index.js:76:3)
(node:190919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:190919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
When checking the file is actually there.
When i specifically install 14.2.0 it updates first and that throws the same error.

**To Reproduce**
1. follow install steps
2. see issue on step `sudo mtslack`

**Expected behavior**
launch the app

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: /
 - Version 20.04

**Additional context**
 node -v
v10.19.0
 npm -v
6.14.4

default apt node and npm

**Comment by mallowigi** [comment]
try to reinstall mtslack. I've updated the dependencies so there's a chance it's related to that. (`npm reinstall mtslack`)

**Comment by jellevanhees** [comment]
that doesn't seem to do the trick. maybe it is also important to know this is the very first time i try to install the tool.
Also `npm reinstall mtslack` didn't work for me i had to `npm uninstall mtslack` and `npm install mtslack`

**Comment by mallowigi** [comment]
Hmmm I have no idea... I'll try to look if I can find a linux machine to test on

**Comment by jellevanhees** [comment]
Thanks that would be cool. This tool seems really awesome so im hyped to install it. 
Which npm and node versions do you use?

**Comment by jellevanhees** [comment]
updated to node 12.19.0 and reinstalled but did not fix the issue

**Comment by mallowigi** [comment]
yeah it looks like it is looking for a font that is unavailable. But I looked in the dependency and the font should be there, so I assume this could be an OS issue.

**Comment by jellevanhees** [comment]
I can confirm that the file he is looking for is actually there and i run it with sudo so permissions should be ok.

**Comment by zanix** [comment]
I think this is a case sensitivity issue, the code is looking for `whimsy.flf` when the file name is `Whimsy.flf`

I altered `main.js` on line 12 and changed `font: sample(['whimsy']),` to `font: sample(['Whimsy']),`
```javascript
async function run() {
  console.log(chalk.yellow(figlet.textSync('mtslack', {
    font: sample(['Whimsy']),
    horizontalLayout: 'default',
    verticalLayout: 'default',
    width: 80,
    whitespaceBreak: true
  })));
```

And now it works.

**Comment by mallowigi** [comment]
Weird, it doesnt' bother me in Mac...

**Comment by zanix** [comment]
Mac and Windows are generally case insensitive for file paths whereas Linux usually is case sensitive

**Comment by mallowigi** [comment]
alright, good catch!

**Comment by Shabinder** [comment]
same issue here to, OS: Manjaro
