### ISSUE TITLE
Invisible System Tray Icon

### ISSUE THREAD

**Issue by YourMCGeek** [mallowigi/mtslack#56]
**Describe the bug**
System Tray icon is now invisible after installing mtslack. 

**To Reproduce**
1. Install Slack Production 4.12.0 64-bit
2. Install mtslack
3. Launch Slack
4. Observe system Tray icon

**Expected behavior**
System Tray icon should be the same as default slack. The slack logo should be present, along with indicators of unread messages and mentions. 

**Screenshots**
![Gif](https://i.imgur.com/MHjGngh.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit 
 - Browser: Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)
 - Slack Version 4.12.0 Production (3b5e52a-s@1609637775)

**Additional context**
Slack works and looks wonderful during this issue, however as I often have Slack minimized the system tray icon is my only way to know if I have unread messages without tabbing back to Slack. Prior to installation, the system tray icon was visible and worked as expected. I've fresh installed Slack prior to installation of mtslack, however it doesn't appear that any system file locations have been changed. 

As I had the same issue per #45 I had to alter the installation script slightly. The script was detecting my archtype being 64 bit and therefore looking for `app64.asr` where I only had `app.asr`. To make the installation run, I simply deleted the ARCH variable here: https://github.com/mallowigi/mtslack/blob/master/lib/consts.js#L6

**Comment by mallowigi** [comment]
Hmmm ok... I never tried on windows but it's weird that it affects the tray icon... I'll try to check when I'll be able to get a hold on a Windows machine

**Comment by YourMCGeek** [comment]
@mallowigi -- Wonderful thank you. Please let me know if you need any additional information, screenshots, gifs, etc. in the meantime. I really enjoy your product, but do miss my unread indicator!

**Comment by infinitum213** [comment]
I've had the same issue here using Windows 10 the last couple of months.
However, I've just done an update of mtslack to the latest version 21.8 and it appears to be working and visible as normal now.
@YourMCGeek is this still a problem for you on the latest version?

**Comment by YourMCGeek** [comment]
Quite honestly, I haven't used the product since making this issue as I just forgot about it (and this issue) when moving to my laptop from my main desktop workstation. I will hopefully try to use the product again within the next 48 hours.
