### ISSUE TITLE
Stops working for the new version of Slack

### ISSUE THREAD

**Issue by anebz** [mallowigi/mtslack#58]
**Describe the bug**
I updated Slack to its newest version and mtslack stopped working. When I try to run it, it gives me an error.

**To Reproduce**
1. Update Slack to Production 4.12.2 64-bit
2. Mtslack tweaks stop working, run `mtslack` on the terminal again
3. Click 'Apply tweaks'

```shell
? Please select an command Apply tweaks

Adding Tweaks Code to Slack...

(node:15840) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile 'C:\Users\aberasategi\AppData\Local\slack\app-4.12.2\resources/app-x64.asar' -> 'C:\Users\aberasategi\AppData\Local\slack\app-4.12.2\resources/app-x64.asar.backup'
    at Object.copyFileSync (fs.js:1991:3)
    at Object.exports.apply (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:174:6)
    at Object.exports.selectTheme (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:212:8)
    at Object.exports.change (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:203:8)
    at exports.execute (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\lib\command.js:218:12)
    at run (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\main.js:32:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AutoUpdate.<anonymous> (C:\Users\aberasategi\AppData\Roaming\npm\node_modules\mtslack\main.js:60:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**
 - OS: Windows 10, 64 bit

**Additional context**
There is no `app-x64.asar` file in `C:\Users\aberasategi\AppData\Local\slack\app-4.12.2\resources\`, there's only `app.asar`. I tried changing the mtslack code to take that file instead, then 'Apply tweaks' is executed normally but Slack is unchanged.

**Comment by MuathIbnHassan** [comment]
I changed the name then build it and it's working

check [my comment](https://github.com/mallowigi/mtslack/issues/57#issuecomment-759706951) in #57

**Comment by mallowigi** [comment]
Yes apparently app-x64 is only for MacOSx. I don't have a windows machine at home so I didn't imagine this would be an issue.

I'll fix it whenever I can get my hands on a Windows.

**Comment by MuathIbnHassan** [comment]
I am using macOS, the name changed to `app.asar` also in the last update using brew cask

sorry I didn't mention that in the reply

**Comment by mallowigi** [comment]
I see, so this is also a difference between the versions downloaded from the AppStore with the others

**Comment by mallowigi** [comment]
Ok i've released a new version that fixes the said issue. Please update and check that everything works.
