### ISSUE TITLE
Support macos brew installations

### ISSUE THREAD

**Issue by simPod** [mallowigi/mtslack#61]
**Is your feature request related to a problem? Please describe.**

I noticed this comment https://github.com/mallowigi/mtslack/issues/57#issuecomment-754710706 It says you have to install slack from app store.

I don't have app store, I ripped it from macos. Brew installations are simpler so I use that.

**Describe the solution you'd like**

`brew install slack` installs slack to my PC. I'd like mtslack to apply tweaks to that installation

**Describe alternatives you've considered**

~~A clear and concise description of any alternative solutions or features you've considered.~~

**Additional context**

Apply Tweaks does nothing now. Also, there's no error clarifying it, so users might get confused why it's not working.

**Comment by mallowigi** [comment]
As I said in the other thread, I have no possibility to guess the install location. Maybe a way to specify the location manually would suffice?

**Comment by simPod** [comment]
Yes, or it might try to read an ENV var if set? `SLACK_APP_PATH` or sth.

**Comment by mallowigi** [comment]
also interesting. Thanks!

Do you think you can do a PR?

**Comment by simPod** [comment]
Yes

**Comment by simPod** [comment]
https://github.com/mallowigi/mtslack/issues/62
