### ISSUE TITLE
Support different Slack.app locations

### ISSUE THREAD

**Issue by rafa-as** [mallowigi/mtslack#62]
**Is your feature request related to a problem? Please describe.**
If you want to install Slack into a different location you can't install (or update) mtslack.

**Describe the solution you'd like**
Brings the possibility to provide (or auto search) an alternative location of Slack app.

**Describe alternatives you've considered**
I think that we only have two options:

1. Move app to Applications folder, install mtslack, apply tweaks and move back the app to the initial location
2. Provide the installer an alternative location (or auto search to locate the Slack app)

**Comment by mallowigi** [comment]
Interesting idea. I'll try to implement that.

But I'm not sure about the permissions regarding non-standard locations.

**Comment by rafa-as** [comment]
I think that a good approach could be to search just under /Applications folder. For example, in my case, I have my apps organized in folders inside Applications.

**Comment by rafa-as** [comment]
Or just for reordered apps downloaded from App Store. The 99% of apps from AppStore or outside it can be placed everywhere inside /Applications path.

**Comment by mallowigi** [comment]
On another thread they suggested to use an environment variable, such as `SLACK_APP`. WDYT?

**Comment by rafa-as** [comment]
> On another thread they suggested to use an environment variable, such as `SLACK_APP`. WDYT?

Could be a workaround, but I think that an auto-discover or a prompt in the installation process would be great.

**Comment by simPod** [comment]
@rafa-as how should the autodiscover work? Running `find / -name "Slack.app"` takes ages. Though it seems that installing through brew copies `.app` into `Applications.

```
/usr/local/Caskroom/slack/4.13.0/Slack.app
/System/Volumes/Data/usr/local/Caskroom/slack/4.13.0/Slack.app
/System/Volumes/Data/Applications/Slack.app
/Applications/Slack.app
```

**Comment by rafa-as** [comment]
I think that a good idea it's to search in the most common locations like /Applications. Make no sense to search at root path.

I guess that we have 3 options:

1. Autodiscover just for concrete places
2. Prompt for Slack path on the installation process
3. Set an environment variable

What do you think?

**Comment by mallowigi** [comment]
Hi, quick update: I released a new version with support for optional paths.

However I must say that I didn't test it in Linux or Windows. Please tell me if that solves the issue, thanks!
