### ISSUE TITLE
Toggling tweaks hot keys not working on Mac

### ISSUE THREAD

**Issue by chris-larsen** [mallowigi/mtslack#65]
**Describe the bug**
Trying to toggle tweaks with the hot keys provided (for instance, `CTRL`+`SHIFT`+`M` for monospaced font) and I have it enabled in tweak settings, but none of the hot key combinations seem to work on my install. I installed through the App store, themes work great and I was able to cycle through themes using the tweak toolbar to get to the one I wanted (though I never had an apply tweak/theme option from the command line, and the only way to get to a theme is by using the toolbar). 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2
 - Device: M1 Macbook Air
 - MTSlack version: 17.1.0

**Comment by mallowigi** [comment]
My bad, the shortcut is actually Ctrl-Alt-<> 

I'll fix the doc, thanks!

**Comment by chris-larsen** [comment]
> My bad, the shortcut is actually Ctrl-Alt-<>
> 
> I'll fix the doc, thanks!

Just curious is the control custom fonts supposed to change the system wide font for Slack? I noticed when I toggle the custom monospaced font option, it changes what's in code blocks just fine. But the custom fonts (ctrl+alt+f) doesn't do anything

**Comment by mallowigi** [comment]
Hmm... How are you defining the custom font? It's not the same as monospace font as you should only put the font-family, not the size. I know it's not very user-friendly, maybe I'll replace with a dropdown in the future.
