### ISSUE TITLE
apply tweaks says succeeds but doesn't 

### ISSUE THREAD

**Issue by rcompier** [mallowigi/mtslack#66]
mtslack says it's been applied, however it doesn't effect slack. (slack-desktop) downloaded the .deb from the official website.
The tweaks however worked before the weekend and now it was just removed.

1. Install mtslack from the docs
2. Run the command in a terminal with sudo
3. Select the option to apply tweaks

**Expected behavior**
After running the command and restarting slack it should be applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/21107109/111998580-726ca500-8b1c-11eb-8cf3-15dc0cd0e885.png)

Ubuntu 20.04

**Comment by mallowigi** [comment]
Started working on this one, but I have other more urgent issues in other works.
