### ISSUE TITLE
does not apply theme

### ISSUE THREAD

**Issue by adandekar-sfdc** [mallowigi/mtslack#71]
**Describe the bug**
With the latest version of slack and mtslack, after I run the mtslack command with sudo permissions it doesn't give the option to Apply Tweaks as in prev versions. and with that said the tweaks are not applied

**To Reproduce**
1. go to terminal
2. run `mtslack` command

**Expected behavior**
I should see option to Apply tweaks

**Screenshots**
![image](https://user-images.githubusercontent.com/58186826/116740501-f468ad00-a9a9-11eb-9e95-38127e636745.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Catalina 10.15.7]
 - Slack native app
 - Slack Version 4.15.0

**Additional context**

**Comment by mallowigi** [comment]
I have no idea what is going on. Which version of node are you using? Is the slack app installed in the applications folder?

**Comment by adandekar-sfdc** [comment]
my node version is v14.15.5 @mallowigi
